BUY = 'buy'
TOTAL_VALUE = 'total_value'
USDT = 'usdt'
INR = 'inr'
TICKER = 'ticker'
VOLUME = 'vol'
UP_ARROW = '\u2191'
DOWN_ARROW = '\u2193'
RUPEE = '₹'
TOKEN_SYMBOLS = {'BTC': '₿', 'ETH': '⟠', 'XRP': '✕', 'ADA': '₳', 'THETA': 'ϑ', 'ALGO': 'Ⱥ', 'USDT': '₮', 'INR': '₹'}
CURRENCY = 'currency'
ORIGINAL = 'original'
SELL = 'sell'
TYPE = SELL
